name: Build JAR and Deploy to UTServer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21.0.6
      uses: actions/setup-java@v2
      with:
        java-version: '21.0.6'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Deploy using SSH
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        local-dir: ./target/
        server-dir: ~/apps/spring-service/
        
    - name: Restart Application
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 2222
        script: |
          cd ~/apps/spring-service
          pkill -f UTServer || true
          nohup java -jar target/UTServer-**.jar > app.log 2>&1 &
